name: Node CI

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14]

    env:
      CI: true

    steps:
    - name: Checkout ${{ github.sha }}
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@c46424eee26de4078d34105d3de3cc4992202b1e
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
    - name: Build
      run: npm run build
